#!/bin/sh

# // 用ldd自动推导出来qt各模块的依赖关系

libs=$(ls /usr/lib/libQt5*.so)

fname=qtmodeps_gened.go
echo -e "package main\n" > $fname
echo -e "// auto generated by genmodeps.sh, do not edit.\n" >> $fname
qtver=$(qmake -v | tail -n 1 | awk '{print $4}')
echo -e "// for version: $qtver \n" >> $fname
echo -e "var modDepsAll = map[string][]string{\n" >> $fname

for lib in $libs; do
    # echo "$lib"
    deps=$(ldd $lib | grep "libQt5" | awk '{print $1}' | awk -F5 '{print $2}' | awk -F\. '{print $1}')
    deparr=""
    deparro=""
    for depo in $deps; do
        dep=${depo,,}
        # echo "$lib depeneds: $dep"
        deparr="\"$dep\", $deparr"
        deparro="\"$depo\", $deparro"
    done
    libnameo=$(echo "$lib" | awk -F5 '{print $2}' | awk -F\. '{print $1}')
    libname=${libnameo,,}
    echo "$libnameo depeneds: $deparro"
    # echo -e "\"$libname\": []string{$deparr}," >> $fname
    echo -e "\"$libnameo\": []string{$deparro}," >> $fname
done

echo -e "\"AndroidExtras\": []string{\"Core\", }," >> $fname
echo -e "\"WinExtras\": []string{\"Core\", \"Gui\", \"Widgets\", }," >> $fname
echo -e "\"MacExtras\": []string{\"Core\", \"Gui\",}," >> $fname
#echo -e "\"androidextras\": []string{\"core\", }," >> $fname
#echo -e "\"winextras\": []string{\"core\", \"gui\",}," >> $fname
#echo -e "\"macextras\": []string{\"core\", \"gui\",}," >> $fname
echo -e "}\n" >> $fname

set -x
gofmt -w $fname


