package main

import (
	"strings"

	funk "github.com/thoas/go-funk"
)

// auto generated by genmodeps.sh, do not edit.

// for version: 5.10.0
var modDepsAll = map[string][]string{

	"3DAnimation":            []string{"Network", "Concurrent", "Core", "Gui", "3DCore", "3DRender"},
	"3DCore":                 []string{"Core", "Network", "Gui"},
	"3DExtras":               []string{"Network", "Concurrent", "Core", "Gui", "3DCore", "3DLogic", "3DInput", "3DRender"},
	"3DInput":                []string{"Network", "Core", "Gui", "3DCore"},
	"3DLogic":                []string{"Network", "Gui", "Core", "3DCore"},
	"3DQuickAnimation":       []string{"Network", "Concurrent", "Gui", "Core", "Qml", "3DCore", "3DRender", "3DAnimation"},
	"3DQuickExtras":          []string{"Network", "Concurrent", "Quick", "Core", "Qml", "Gui", "3DCore", "3DLogic", "3DRender", "3DQuick", "3DInput", "3DExtras"},
	"3DQuickInput":           []string{"Network", "Gui", "Core", "Qml", "3DCore", "3DInput"},
	"3DQuickRender":          []string{"Network", "Concurrent", "Gui", "Core", "Qml", "3DCore", "3DRender"},
	"3DQuickScene2D":         []string{"Network", "Concurrent", "Core", "Qml", "Gui", "Quick", "3DCore", "3DRender"},
	"3DQuick":                []string{"Network", "Core", "Qml", "Gui", "Quick", "3DCore"},
	"3DRender":               []string{"Network", "Concurrent", "Core", "Gui", "3DCore"},
	"Bluetooth":              []string{"DBus", "Core"},
	"Charts":                 []string{"Core", "Gui", "Widgets"},
	"Concurrent":             []string{"Core"},
	"Core":                   []string{},
	"DataVisualization":      []string{"Core", "Gui"},
	"DBus":                   []string{"Core"},
	"Declarative":            []string{"Core", "Network", "XmlPatterns", "Sql", "Script", "Gui", "Widgets"},
	"DesignerComponents":     []string{"Core", "Xml", "Gui", "Widgets", "Designer"},
	"Designer":               []string{"Core", "Xml", "Gui", "Widgets"},
	"EglFSDeviceIntegration": []string{"Core", "DBus", "Gui"},
	"EglFsKmsSupport":        []string{"DBus", "Core", "Gui", "EglFSDeviceIntegration"},
	"Gamepad":                []string{"Core", "Gui"},
	"GLib-2":                 []string{"Core"},
	"GStreamer-1":            []string{"Core", "GLib-2"},
	"GStreamerQuick-1":       []string{"Network", "Qml", "Core", "Gui", "GLib-2", "Quick", "GStreamer-1"},
	"GStreamerUi-1":          []string{"Core", "Gui", "Widgets", "GLib-2", "OpenGL", "GStreamer-1"},
	"GStreamerUtils-1":       []string{"Core", "GLib-2", "GStreamer-1"},
	"Gui":                    []string{"Core"},
	"Help":                   []string{"Core", "Sql", "Gui", "Widgets"},
	"Inline":                 []string{"QuickTemplates2", "Core", "Network", "Gui", "Widgets", "Qml", "Quick", "Multimedia", "Svg", "QuickWidgets", "QuickControls2"},
	"Location":               []string{"Network", "Core", "Qml", "Gui", "Quick", "Positioning"},
	"MultimediaGstTools":     []string{"Network", "OpenGL", "Core", "Gui", "Widgets", "Multimedia", "MultimediaWidgets"},
	"MultimediaQuick":        []string{"Qml", "Network", "Core", "Gui", "Quick", "Multimedia"},
	"Multimedia":             []string{"Core", "Gui", "Network"},
	"MultimediaWidgets":      []string{"Network", "OpenGL", "Core", "Gui", "Widgets", "Multimedia"},
	"NetworkAuth":            []string{"Core", "Network"},
	"Network":                []string{"Core"},
	"Nfc":                    []string{"DBus", "Core"},
	"OpenGL":                 []string{"Core", "Gui", "Widgets"},
	"PositioningQuick":       []string{"Core", "Network", "Qml", "Positioning"},
	"Positioning":            []string{"Core"},
	"PrintSupport":           []string{"Core", "Gui", "Widgets"},
	"Qml":                    []string{"Core", "Network"},
	"QuickControls2":         []string{"Network", "QuickTemplates2", "Core", "Qml", "Gui", "Quick"},
	"QuickParticles":         []string{"Network", "Core", "Gui", "Qml", "Quick"},
	"Quick":                  []string{"Core", "Network", "Gui", "Qml"},
	"QuickTemplates2":        []string{"Network", "Core", "Qml", "Gui", "Quick"},
	"QuickTest":              []string{"Network", "Qml", "Quick", "Core", "Gui", "Widgets", "Test"},
	"QuickWidgets":           []string{"Network", "Core", "Gui", "Widgets", "Qml", "Quick"},
	"RemoteObjects":          []string{"Core", "Network"},
	"Script":                 []string{"Core"},
	"ScriptTools":            []string{"Gui", "Widgets", "Script", "Core"},
	"Scxml":                  []string{"Network", "Core", "Qml"},
	"Sensors":                []string{"Core"},
	"SerialBus":              []string{"SerialPort", "Network", "Core"},
	"SerialPort":             []string{"Core"},
	"Sql":                    []string{"Core"},
	"Svg":                    []string{"Core", "Gui", "Widgets"},
	"Test":                   []string{"Core"},
	"TextToSpeech":           []string{"Core"},
	"WaylandClient":          []string{"DBus", "Core", "Gui"},
	"WaylandCompositor":      []string{"Network", "Core", "Qml", "Gui", "Quick"},
	"WebChannel":             []string{"Network", "Core", "Qml"},
	"WebEngineCore":          []string{"Qml", "Positioning", "WebChannel", "Core", "Network", "Gui", "Quick"},
	"WebEngine":              []string{"Positioning", "Network", "Core", "Qml", "WebChannel", "Gui", "Quick", "WebEngineCore"},
	"WebEngineWidgets":       []string{"Qml", "Positioning", "WebChannel", "QuickWidgets", "Core", "Network", "Gui", "Widgets", "PrintSupport", "Quick", "WebEngineCore"},
	"WebKit":                 []string{"Core", "Network", "Qml", "Gui", "Sensors", "Positioning", "WebChannel", "Quick"},
	"WebKitWidgets":          []string{"Qml", "Sensors", "Positioning", "WebChannel", "Quick", "Core", "Network", "Gui", "WebKit", "Widgets", "PrintSupport"},
	"WebSockets":             []string{"Core", "Network"},
	"WebView":                []string{"Network", "Qml", "Quick", "Core", "Gui"},
	"Widgets":                []string{"Core", "Gui"},
	"X11Extras":              []string{"Core", "Gui"},
	"XcbQpa":                 []string{"Core", "DBus", "Gui"},
	"XdgIconLoader":          []string{"Core", "Gui"},
	"Xdg":                    []string{"Core", "Gui", "Widgets", "XdgIconLoader", "DBus", "Xml"},
	"XmlPatterns":            []string{"Core", "Network"},
	"Xml":                    []string{"Core"},
	"AndroidExtras":          []string{"Core"},
	"WinExtras":              []string{"Core", "Gui", "Widgets"},
	"MacExtras":              []string{"Core", "Gui"},
}

func init() {
	// reinit modDepsAll's lowercase part
	lcmodDepsAll := map[string][]string{}
	for k, vs := range modDepsAll {
		deps := []string{}
		for _, v := range vs {
			deps = append(deps, strings.ToLower(v))
		}
		lcmodDepsAll[strings.ToLower(k)] = deps
	}
	for k, vs := range lcmodDepsAll {
		modDepsAll[k] = vs
	}
}

func rebuildModDepsAll(qtver string) {
	// WebEngineWidgets -= PrintSupport
	if strings.HasPrefix(qtver, "5.7") || strings.HasPrefix(qtver, "5.6") {
		deps := modDepsAll["WebEngineWidgets"]
		newdeps := funk.FilterString(deps, func(s string) bool { return s != "PrintSupport" })
		modDepsAll["WebEngineWidgets"] = newdeps

		deps = modDepsAll["webenginewidgets"]
		newdeps = funk.FilterString(deps, func(s string) bool { return s != "printsupport" })
		modDepsAll["webenginewidgets"] = newdeps
	}
	// - QuickControls2
	if strings.HasPrefix(qtver, "5.6") {
		delete(modDepsAll, "QuickControls2")
		delete(modDepsAll, "quickcontrols2")
	}
}
