#ifndef _QTHDRSRC_H_
#define _QTHDRSRC_H_

// #include <jri.h>
// #include <jri_md.h>
// #include <jritypes.h>
// #include <npapi.h>
// #include <npupp.h>
// #include <q1xcompatibility.h>
#include <qabstractlayout.h>
#include <qaccel.h>
#include <qaccessible.h>
#include <qaction.h>
#include <qapp.h>
#include <qapplication.h>
#include <qarray.h>
#include <qasciicache.h>
#include <qasciidict.h>
#include <qassistantclient.h>
#include <qasyncimageio.h>
#include <qasyncio.h>
#include <qbig5codec.h>
#include <qbitarray.h>
#include <qbitarry.h>
#include <qbitmap.h>
#include <qbrush.h>
#include <qbttngrp.h>
#include <qbuffer.h>
#include <qbuttongroup.h>
#include <qbutton.h>
#include <qcache.h>
#include <qcanvas.h>
#include <qcdestyle.h>
#include <qcheckbox.h>
#include <qchkbox.h>
#include <qcleanuphandler.h>
#include <qclipboard.h>
#include <qclipbrd.h>
#include <qcollect.h>
#include <qcollection.h>
#include <qcolordialog.h>
#include <qcolor.h>
#include <qcombobox.h>
#include <qcombo.h>
#include <qcommonstyle.h>
#include <qcompactstyle.h>
#include <qconfig-dist.h>
#include <qconfig.h>
#include <qconfig-large.h>
#include <qconfig-medium.h>
#include <qconfig-minimal.h>
#include <qconfig-small.h>
#include <qconnect.h>
#include <qconnection.h>
#include <qcstring.h>
#include <qcursor.h>
#include <qdatabrowser.h>
#include <qdatastream.h>
#include <qdatatable.h>
#include <qdataview.h>
#include <qdatetimeedit.h>
#include <qdatetime.h>
#include <qdatetm.h>
#include <qdeepcopy.h>
#include <qdesktopwidget.h>
#include <qdial.h>
#include <qdialog.h>
#include <qdict.h>
#include <qdir.h>
#include <qdns.h>
#include <qdockarea.h>
#include <qdockwindow.h>
#include <qdom.h>
#include <qdragobject.h>
#include <qdrawutil.h>
#include <qdrawutl.h>
#include <qdropsite.h>
#include <qdstream.h>
#include <qeditorfactory.h>
#include <qerrormessage.h>
#include <qeucjpcodec.h>
#include <qeuckrcodec.h>
#include <qevent.h>
#include <qeventloop.h>
#include <qfeatures.h>
#include <qfiledef.h>
#include <qfiledialog.h>
#include <qfiledlg.h>
#include <qfile.h>
#include <qfileinf.h>
#include <qfileinfo.h>
#include <qfocusdata.h>
#include <qfontdatabase.h>
#include <qfontdialog.h>
#include <qfont.h>
#include <qfontinf.h>
#include <qfontinfo.h>
#include <qfontmet.h>
#include <qfontmetrics.h>
#include <qframe.h>
#include <qftp.h>
#include <qgarray.h>
#include <qgb18030codec.h>
#include <qgbkcodec.h>
#include <qgcache.h>
#include <qgdict.h>
#include <qgeneric.h>
#include <qgif.h>
#include <qglcolormap.h>
#include <qgl.h>
#include <qglist.h>
#include <qglobal.h>
#include <qgplugin.h>
#include <qgrid.h>
#include <qgridview.h>
#include <qgroupbox.h>
#include <qgrpbox.h>
#include <qguardedptr.h>
#include <qgvector.h>
#include <qhbox.h>
#include <qhbuttongroup.h>
#include <qheader.h>
#include <qhgroupbox.h>
#include <qhostaddress.h>
#include <qhttp.h>
#include <qiconset.h>
#include <qiconview.h>
#include <qimageformatplugin.h>
#include <qimage.h>
#include <qinputcontextfactory.h>
#include <qinputcontext.h>
#include <qinputcontextplugin.h>
#include <qinputdialog.h>
#include <qintcache.h>
#include <qintcach.h>
#include <qintdict.h>
#include <qinterlacestyle.h>
#include <qiodev.h>
#include <qiodevice.h>
#include <qjiscodec.h>
#include <qjpegio.h>
#include <qjpunicode.h>
#include <qkeycode.h>
#include <qkeysequence.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qlcdnumber.h>
#include <qlcdnum.h>
#include <qlibrary.h>
#include <qlined.h>
#include <qlineedit.h>
#include <qlistbox.h>
#include <qlist.h>
#include <qlistview.h>
#include <qlocale.h>
#include <qlocalfs.h>
#include <qmainwindow.h>
#include <qmap.h>
#include <qmemarray.h>
#include <qmenubar.h>
#include <qmenudata.h>
#include <qmenudta.h>
#include <qmessagebox.h>
#include <qmetaobject.h>
#include <qmetaobj.h>
#include <qmime.h>
#include <qmlined.h>
#include <qmngio.h>
#include <qmodules.h>
#include <qmotifplusstyle.h>
#include <qmotifstyle.h>
#include <qmovie.h>
#include <qmsgbox.h>
#include <qmultilinedit.h>
#include <qmultilineedit.h>
#include <qmutex.h>
#include <qnamespace.h>
#include <qnetwork.h>
#include <qnetworkprotocol.h>
#include <qnp.h>
#include <qobjcoll.h>
#include <qobjdefs.h>
#include <qobjectcleanuphandler.h>
#include <qobjectdefs.h>
#include <qobjectdict.h>
#include <qobject.h>
#include <qobjectlist.h>
#include <qpaintdc.h>
#include <qpaintdevicedefs.h>
#include <qpaintdevice.h>
#include <qpaintdevicemetrics.h>
#include <qpaintd.h>
#include <qpainter.h>
#include <qpair.h>
#include <qpalette.h>
#include <qpdevmet.h>
#include <qpen.h>
#include <qpicture.h>
#include <qpixmapcache.h>
#include <qpixmap.h>
#include <qplatinumstyle.h>
#include <qpmcache.h>
#include <qpngio.h>
#include <qpntarry.h>
#include <qpointarray.h>
#include <qpoint.h>
#include <qpolygonscanner.h>
#include <qpopmenu.h>
#include <qpopupmenu.h>
#include <qprintdialog.h>
#include <qprinter.h>
#include <qprndlg.h>
#include <qprocess.h>
#include <qprogbar.h>
#include <qprogdlg.h>
#include <qprogressbar.h>
#include <qprogressdialog.h>
#include <qpsprn.h>
#include <qptrcollection.h>
#include <qptrdict.h>
#include <qptrlist.h>
#include <qptrqueue.h>
#include <qptrstack.h>
#include <qptrvector.h>
#include <qpushbt.h>
#include <qpushbutton.h>
#include <qqueue.h>
#include <qradiobt.h>
#include <qradiobutton.h>
#include <qrangecontrol.h>
#include <qrangect.h>
#include <qrect.h>
#include <qregexp.h>
#include <qregion.h>
#include <qrtlcodec.h>
#include <qscrbar.h>
#include <qscrollbar.h>
#include <qscrollview.h>
#include <qsemaphore.h>
#include <qsemimodal.h>
#include <qserversocket.h>
#include <qsession.h>
#include <qsessionmanager.h>
#include <qsettings.h>
#include <qsgistyle.h>
#include <qshared.h>
#include <qsignal.h>
#include <qsignalmapper.h>
#include <qsignalslotimp.h>
#include <qsimplerichtext.h>
#include <qsizegrip.h>
#include <qsize.h>
#include <qsizepolicy.h>
#include <qsjiscodec.h>
#include <qslider.h>
#include <qsocketdevice.h>
#include <qsocket.h>
#include <qsocketnotifier.h>
#include <qsocknot.h>
#include <qsortedlist.h>
#include <qsound.h>
#include <qspinbox.h>
#include <qsplashscreen.h>
#include <qsplitter.h>
#include <qsqlcursor.h>
#include <qsqldatabase.h>
#include <qsqldriver.h>
#include <qsqldriverplugin.h>
#include <qsqleditorfactory.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlform.h>
#include <qsql.h>
#include <qsqlindex.h>
#include <qsqlpropertymap.h>
#include <qsqlquery.h>
#include <qsqlrecord.h>
#include <qsqlresult.h>
#include <qsqlselectcursor.h>
#include <qstack.h>
#include <qstatusbar.h>
#include <qstring.h>
#include <qstringlist.h>
#include <qstrlist.h>
#include <qstrvec.h>
#include <qstylefactory.h>
#include <qstyle.h>
#include <qstyleplugin.h>
#include <qstylesheet.h>
#include <qsyntaxhighlighter.h>
#include <qtabbar.h>
#include <qtabdialog.h>
#include <qtabdlg.h>
#include <qtable.h>
#include <qtabwidget.h>
#include <qtextbrowser.h>
#include <qtextcodecfactory.h>
#include <qtextcodec.h>
#include <qtextcodecplugin.h>
#include <qtextedit.h>
#include <qtextstream.h>
#include <qtextview.h>
#include <qt.h>
#include <qthread.h>
#include <qthreadstorage.h>
#include <qtimer.h>
#include <qtl.h>
#include <qtmultilineedit.h>
#include <qtoolbar.h>
#include <qtoolbox.h>
#include <qtoolbutton.h>
#include <qtooltip.h>
#include <qt_pch.h>
#include <qtranslator.h>
#include <qtsciicodec.h>
#include <qtstream.h>
#include <qttableview.h>
#include <qurl.h>
#include <qurlinfo.h>
#include <qurloperator.h>
#include <qutfcodec.h>
#include <quuid.h>
#include <qvalidator.h>
#include <qvaluelist.h>
#include <qvaluestack.h>
#include <qvaluevector.h>
#include <qvariant.h>
#include <qvbox.h>
#include <qvbuttongroup.h>
#include <qvector.h>
#include <qvfbhdr.h>
#include <qvgroupbox.h>
#include <qwaitcondition.h>
#include <qwhatsthis.h>
#include <qwidcoll.h>
#include <qwidgetfactory.h>
#include <qwidget.h>
#include <qwidgetintdict.h>
#include <qwidgetlist.h>
#include <qwidgetplugin.h>
#include <qwidgetstack.h>
#include <qwindefs.h>
#include <qwindowdefs.h>
#include <qwindow.h>
#include <qwindowsstyle.h>
#include <qwinexport.h>
#include <qwizard.h>
#include <qwmatrix.h>
#include <qworkspace.h>
#include <qxml.h>

#endif
